### ISSUE TITLE
Remove empty playlists periodically

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#41] opened 2015-03-06 18:45 UTC
If a playlist with 0 songs in it has existed for more than a day, it should be removed.

**Comment by mutantmonkey** [comment] 2015-03-06 19:21
How do you envision this working? Do you want to have a script that's called via cron or something?

**Comment by telnoratti** [comment] 2015-03-06 19:37
I imagine a cronjob script that looks only at playlists older than a day would work. In /trackman/api/search there is a join line that could be pretty handy for this.

**Comment by telnoratti** [comment] 2015-03-14 00:03
Since we have it now, this should be made as a celery task.

**Comment by matthazinski** [comment] 2015-03-14 03:01
:+1:

**Comment by mutantmonkey** [comment] 2015-03-29 03:15
#128 was filed as a dupe of this, which I implemented in aed25fa9795cd6d7686ba58acd1a01080c3b19ea.

**Closed by mutantmonkey** 2015-03-29 03:15 UTC
Labels: cosmetic, enhancement
