### ISSUE TITLE
when typing in trackman fields, exactly what you want appears in autocomplete, then almost instantly disappears when you move the mouse.

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#285] opened 2017-04-17 23:00 UTC

**Comment by mutantmonkey** [comment] 2017-04-18 03:39
We don't have any mouse move events for autocomplete, so something else is at play here.

**Comment by mutantmonkey** [comment] 2017-04-18 04:30
I think the issue is again that searches are not completing in time and DJs are starting to move their mouse to select something. A potential fix for this is to cancel any pending autocomplete timers (and maybe API calls too).

**Comment by mutantmonkey** [comment] 2017-04-23 20:34
This should be fixed in 06fe15bf42abaad596596491e92b0ca25e773510.

**Closed by mutantmonkey** 2017-04-23 20:34 UTC
Labels: bug
