### ISSUE TITLE
"Flag" link on playlist page

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#91] opened 2015-03-11 01:13 UTC
Each track in a playlist should contain a "flag" link to allow you to report an entry to one or more people (e.g. MD, FMPD, DJ, TD, CE) by selecting from a drop-down list of various reasons (e.g. bad metadata, bad music, bad sound quality, FCC violation).

**Comment by mutantmonkey** [comment] 2015-03-11 06:19
I think this is going to complicate the UI too much, and it shouldn't be the responsibility of the visitor or listener to ensure WUVT has things together.

**Comment by matthazinski** [comment] 2015-03-11 18:05
Maybe we can whitelist IPs like trackman does?

**Comment by matthazinski** [comment] 2015-03-13 02:42
Better yet, instead of emails, let's use Twilio to direct complaints to the request line.

**Comment by andreimarcu** [comment] 2015-03-13 02:43
:+1:

**Comment by mutantmonkey** [comment] 2015-03-13 07:03
This is a dupe of #74.

**Closed** 2015-03-13 07:07 UTC
Labels: enhancement
