### ISSUE TITLE
chart ranking is broken: all items are #1

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#265] opened 2017-02-26 03:50 UTC

**Comment by mutantmonkey** [comment] 2017-02-26 04:05
This may have been caused by a library upgrade.

**Comment by mutantmonkey** [comment] 2017-02-26 05:19
This is pallets/jinja#641. We may want to rework how the ranking works because apparently this wasn't supposed to work like this.

**Comment by echarlie** [comment] 2017-07-20 01:08
broken again in the current release

**Comment by echarlie** [comment] 2017-08-13 03:20
How do people feel about disabling ranking for now, outright?

**Comment by mutantmonkey** [comment] 2017-08-20 19:23
We will not disable the ranking. A permanent fix for this is included in #298.

**Closed** 2017-08-20 20:31 UTC
Labels: bug, template
