### ISSUE TITLE
Allow post categories to be hidden

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#83] opened 2015-03-09 00:23 UTC
There should be a boolean option in the admin panel to determine whether a category is shown on the sidebar.

**Comment by bkodres93** [comment] 2015-09-21 04:30
duplicate?

**Comment by bkodres93** [comment] 2015-09-21 18:27
duplicate of https://github.com/wuvt/wuvt-site/issues/157

**Closed by bkodres93** 2015-09-21 18:27 UTC
Labels: cosmetic, enhancement
