### ISSUE TITLE
ui-datepicker-div on blog pages is causing display issues

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#87] opened 2015-03-09 06:39 UTC
<div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"></div> 

is present on blog pages for some reason, and shows up as a thin rectangular white box.

**Comment by matthazinski** [comment] 2015-03-11 01:27
#86 is causing this

**Comment by mutantmonkey** [comment] 2015-03-11 06:00
This is basically a dupe of #86, there is no reason to keep this open.

**Closed by mutantmonkey** 2015-03-11 06:00 UTC
